### ISSUE TITLE
Can't start server: [Error: [npm-probe] failed to updated feed]

### ISSUE THREAD

**Issue by marcellodesales** [nodejitsu/browsenpm.org#41]
Tried starting the server and I can't... any idea why this would happen?

root@822cb8633860:/runtime# npm start

> browsenpm@0.5.1 start /runtime
> bin/server

[Error: [npm-probe] failed to updated feed]

fs.js:771
  return binding.unlink(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/runtime/node_modules/npm-search-pagelet/58fe96c0957f08d3ff2e041267fc112f-0'
    at Object.fs.unlinkSync (fs.js:771:18)
    at ChildProcess.exit (/runtime/node_modules/npm-search-pagelet/httpsgc.js:107:20)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)

npm ERR! browsenpm@0.5.1 start: `bin/server`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the browsenpm@0.5.1 start script.
npm ERR! This is most likely a problem with the browsenpm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bin/server
npm ERR! You can get their info via:
npm ERR!     npm owner ls browsenpm
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-431.1.2.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /runtime
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /runtime/npm-debug.log
npm ERR! not ok code 0

**Comment by marcellodesales** [comment]
Closing this one in favor of where the main issue is... https://github.com/nodejitsu/npm-search-pagelet/issues/4
